export const HEAD: string[] = [
   'afro',
   'bangs',
   'bangs2',
   'bantuKnots',
   'bear',
   'bun',
   'bun2',
   'buns',
   'cornrows',
   'cornrows2',
   'dreads1',
   'dreads2',
   'flatTop',
   'flatTopLong',
   'grayBun',
   'grayMedium',
   'grayShort',
   'hatBeanie',
   'hatHip',
   'hijab',
   'long',
   'longAfro',
   'longBangs',
   'longCurly',
   'medium1',
   'medium2',
   'medium3',
   'mediumBangs',
   'mediumBangs2',
   'mediumBangs3',
   'mediumStraight',
   'mohawk',
   'mohawk2',
   'noHair1',
   'noHair',
   'noHair3',
   'pomp',
   'shaved1',
   'shaved2',
   'shaved3',
   'short1',
   'short2',
   'short3',
   'short4',
   'short5',
   'turban',
   'twists',
   'twists2',
];

export const FACE: string[] = [
   'angryWithFang',
   'awe',
   'blank',
   'calm',
   'cheeky',
   'concerned',
   'concernedFear',
   'contempt',
   'cute',
   'cyclops',
   'driven',
   'eatingHappy',
   'explaining',
   'eyesClosed',
   'fear',
   'hectic',
   'lovingGrin1',
   'lovingGrin2',
   'monster',
   'old',
   'rage',
   'serious',
   'smile',
   'smileBig',
   'smileLOL',
   'smileTeethGap',
   'solemn',
   'suspicious',
   'tired',
   'veryAngry',
];

export const FACIAL_HAIR: string[] = [
   'chin',
   'full',
   'full2',
   'full3',
   'full4',
   'goatee1',
   'goatee2',
   'moustache1',
   'moustache2',
   'moustache3',
   'moustache4',
   'moustache5',
   'moustache6',
   'moustache7',
   'moustache8',
   'moustache9',
];

export const ACCESSORIES: string[] = [
   'eyepatch',
   'glasses',
   'glasses2',
   'glasses3',
   'glasses4',
   'glasses5',
   'sunglasses',
   'sunglasses2',
];

export const MASK: string[] = ['medicalMask', 'respirator'];

export const SKIN_COLOR = [
   'variant01',
   'variant02',
   'variant03',
   'variant04',
   'variant05',
];

export const CLOTHING_COLOR: string[] = [
   'red01',
   'orange01',
   'yellow01',
   'green01',
   'tail01',
   'blue01',
   'pink01',
];

export const HAIR_COLOR: string[] = [
   'variant01',
   'variant02',
   'variant03',
   'variant04',
   'variant05',
   'variant06',
   'variant07',
   'variant08',
   'variant09',
   'variant10',
];
