export const HEAD: string[] = [
   'afro',
   'bangs',
   'bangs2',
   'bantuKnots',
   'bear',
   'bun',
   'bun2',
   'buns',
   'cornrows',
   'cornrows2',
   'dreads1',
   'dreads2',
   'flatTop',
   'flatTopLong',
   'grayBun',
   'grayMedium',
   'grayShort',
   'hatBeanie',
   'hatHip',
   'hijab',
   'long',
   'longAfro',
   'longBangs',
   'longCurly',
   'medium1',
   'medium2',
   'medium3',
   'mediumBangs',
   'mediumBangs2',
   'mediumBangs3',
   'mediumStraight',
   'mohawk',
   'mohawk2',
   'noHair1',
   'noHair',
   'noHair3',
   'pomp',
   'shaved1',
   'shaved2',
   'shaved3',
   'short1',
   'short2',
   'short3',
   'short4',
   'short5',
   'turban',
   'twists',
   'twists2',
];

export const FACE: string[] = [
   'angryWithFang',
   'awe',
   'blank',
   'calm',
   'cheeky',
   'concerned',
   'concernedFear',
   'contempt',
   'cute',
   'cyclops',
   'driven',
   'eatingHappy',
   'explaining',
   'eyesClosed',
   'fear',
   'hectic',
   'lovingGrin1',
   'lovingGrin2',
   'monster',
   'old',
   'rage',
   'serious',
   'smile',
   'smileBig',
   'smileLOL',
   'smileTeethGap',
   'solemn',
   'suspicious',
   'tired',
   'veryAngry',
];

export const FACIAL_HAIR: string[] = [
   'chin',
   'full',
   'full2',
   'full3',
   'full4',
   'goatee1',
   'goatee2',
   'moustache1',
   'moustache2',
   'moustache3',
   'moustache4',
   'moustache5',
   'moustache6',
   'moustache7',
   'moustache8',
   'moustache9',
];

export const ACCESSORIES: string[] = [
   'eyepatch',
   'glasses',
   'glasses2',
   'glasses3',
   'glasses4',
   'glasses5',
   'sunglasses',
   'sunglasses2',
];

export const MASK: string[] = ['medicalMask', 'respirator'];

export const SKIN_COLOR: { label: string; value: string }[] = [
   { value: '694d3d', label: 'Dark Brown' },
   { value: 'ae5d29', label: 'Brown' },
   { value: 'd08b5b', label: 'Tan' },
   { value: 'edb98a', label: 'Light Tan' },
   { value: 'ffdbb4', label: 'Pale' },
];

export const CLOTHING_COLOR: { label: string; value: string }[] = [
   { value: '8fa7df', label: 'Periwinkle' },
   { value: '9ddadb', label: 'Light Blue' },
   { value: '78e185', label: 'Light Green' },
   { value: 'e279c7', label: 'Pink' },
   { value: 'e78276', label: 'Salmon' },
   { value: 'fdea6b', label: 'Yellow' },
   { value: 'ffcf77', label: 'Gold' },
];

export const BACKGROUND_COLOR: { label: string; value: string }[] = [
   { value: 'b6e3f4', label: 'Alice Blue' },
   { value: 'c0aede', label: 'Lavender' },
   { value: 'd1d4f9', label: 'Periwinkle Blue' },
   { value: 'ffd5dc', label: 'Light Pink' },
   { value: 'ffdfbf', label: 'Peach' },
];
